export interface Contract{
    id: number,
    name: string,
    status: string,
    modifyBy: string,
    modifyDate: Date,
    description?: string,
    triggerdateLbman: boolean,
    triggerdateSvcscat: boolean,
    triggerdateItem: boolean,
    isinterimtrigger: boolean,
    constraintLbman: boolean,
    constraintSvcscat: boolean,
    constraintItem: boolean,
    purma: boolean,
    nntm: boolean,
    pdbtm: boolean,
    dsart: boolean,
    trigger: number,
    interimtrigger: number,
    constraint: number,
    lbmanEffectivedeadlineinfo: number,
    lbmanProcbasisref: number,
    editable: boolean
}